<a href="https://colab.research.google.com/github/ng328/ML-DL_Projects/blob/main/Tata_ipl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("/content/sample_data/IPL Auction 2022.csv")
df

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
0,1,M,R Ashwin,India,TNCA,35,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,167.0,"CSK, RSP, KXIP, DC",DC,Capped,2 CR,5 CR,Rajasthan Royals
1,1,M,Trent Boult,New Zealand,NaN,32,BOWLER,RHB,LEFT ARM Fast Medium,62.0,"SRH, KKR, DD,MI",MI,Capped,2 CR,8 CR,Rajasthan Royals
2,1,M,Pat Cummins,Australia,NaN,28,ALL-ROUNDER,RHB,RIGHT ARM Fast,37.0,"DD, MI, KKR",KKR,Capped,2 CR,7.25 CR,Kolkata Knight Riders
3,1,M,Shikhar Dhawan,India,DDCA,36,BATSMAN,LHB,-,192.0,"DCH, MI, SRH, DC",DC,Capped,2 CR,8.25 CR,Punjab Kings
4,1,M,Faf Du Plessis,South Africa,NaN,37,BATSMAN,RHB,RIGHT ARM Leg Spin,100.0,"RPS, CSK",CSK,Capped,2 CR,7 CR,Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,53,UAL8,Ansh Patel,India,BCA,20,ALL-ROUNDER,RHB,LEFT ARM Slow Unorthodox,NaN,NaN,NaN,Uncapped,20 L,20 L,Punjab Kings
180,54,UFA8,Ashok Sharma,India,RCA,19,BOWLER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20 L,55 L,Kolkata Knight Riders
181,57,UAL10,Arjun Tendulkar,India,MCA,22,ALL-ROUNDER,LHB,LEFT ARM Fast Medium,0.0,MI,MI,Uncapped,20 L,30 L,Mumbai Indians
182,59,UAL12,Shubham Garhwal,India,RCA,26,ALL-ROUNDER,LHB,LEFT ARM Slow Orthodox,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals
183,60,UAL13,Anunay Singh,India,BICA,29,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals

In [ ]:
df.head()

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
0,1,M,R Ashwin,India,TNCA,35,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,167.0,"CSK, RSP, KXIP, DC",DC,Capped,2 CR,5 CR,Rajasthan Royals
1,1,M,Trent Boult,New Zealand,NaN,32,BOWLER,RHB,LEFT ARM Fast Medium,62.0,"SRH, KKR, DD,MI",MI,Capped,2 CR,8 CR,Rajasthan Royals
2,1,M,Pat Cummins,Australia,NaN,28,ALL-ROUNDER,RHB,RIGHT ARM Fast,37.0,"DD, MI, KKR",KKR,Capped,2 CR,7.25 CR,Kolkata Knight Riders
3,1,M,Shikhar Dhawan,India,DDCA,36,BATSMAN,LHB,-,192.0,"DCH, MI, SRH, DC",DC,Capped,2 CR,8.25 CR,Punjab Kings
4,1,M,Faf Du Plessis,South Africa,NaN,37,BATSMAN,RHB,RIGHT ARM Leg Spin,100.0,"RPS, CSK",CSK,Capped,2 CR,7 CR,Royal Challengers Bangalore

In [ ]:
df.tail()

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
179,53,UAL8,Ansh Patel,India,BCA,20,ALL-ROUNDER,RHB,LEFT ARM Slow Unorthodox,NaN,NaN,NaN,Uncapped,20 L,20 L,Punjab Kings
180,54,UFA8,Ashok Sharma,India,RCA,19,BOWLER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20 L,55 L,Kolkata Knight Riders
181,57,UAL10,Arjun Tendulkar,India,MCA,22,ALL-ROUNDER,LHB,LEFT ARM Fast Medium,0.0,MI,MI,Uncapped,20 L,30 L,Mumbai Indians
182,59,UAL12,Shubham Garhwal,India,RCA,26,ALL-ROUNDER,LHB,LEFT ARM Slow Orthodox,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals
183,60,UAL13,Anunay Singh,India,BICA,29,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals

In [ ]:
df.head(10)

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
0,1,M,R Ashwin,India,TNCA,35,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,167.0,"CSK, RSP, KXIP, DC",DC,Capped,2 CR,5 CR,Rajasthan Royals
1,1,M,Trent Boult,New Zealand,NaN,32,BOWLER,RHB,LEFT ARM Fast Medium,62.0,"SRH, KKR, DD,MI",MI,Capped,2 CR,8 CR,Rajasthan Royals
2,1,M,Pat Cummins,Australia,NaN,28,ALL-ROUNDER,RHB,RIGHT ARM Fast,37.0,"DD, MI, KKR",KKR,Capped,2 CR,7.25 CR,Kolkata Knight Riders
3,1,M,Shikhar Dhawan,India,DDCA,36,BATSMAN,LHB,-,192.0,"DCH, MI, SRH, DC",DC,Capped,2 CR,8.25 CR,Punjab Kings
4,1,M,Faf Du Plessis,South Africa,NaN,37,BATSMAN,RHB,RIGHT ARM Leg Spin,100.0,"RPS, CSK",CSK,Capped,2 CR,7 CR,Royal Challengers Bangalore
5,1,M,Shreyas Iyer,India,MCA,27,BATSMAN,RHB,RIGHT ARM Leg Spin,87.0,DC,DC,Capped,2 CR,12.25 CR,Kolkata Knight Riders
6,1,M,Kagiso Rabada,South Africa,NaN,26,BOWLER,LHB,RIGHT ARM Fast,50.0,DC,DC,Capped,2 CR,9.25 CR,Punjab Kings
7,1,M,Mohammad Shami,India,CAB,32,BOWLER,RHB,RIGHT ARM Fast,77.0,"DCH, KKR, DD, PBKS",PBKS,Capped,2 CR,6.25 CR,Gujarat Titans
8,1,M,David Warner,Australia,NaN,35,BATSMAN,LHB,-,150.0,"DD, SRH",SRH,Capped,2 CR,6.25 CR,Delhi Capitals
9,2,BA1,Shimron Hetmyer,West Indies,NaN,25,BATSMAN,LHB,RIGHT ARM Leg Spin,31.0,"RCB, DC",DC,Capped,1.5 CR,8.5 CR,Rajasthan Royals

In [ ]:
df.size

2944

In [ ]:
df.shape

(184, 16)

In [ ]:
df.ndim

2

In [ ]:
df.values

array([[1, 'M', 'R Ashwin', ..., '2 CR', '5 CR', 'Rajasthan Royals'],
       [1, 'M', 'Trent Boult', ..., '2 CR', '8 CR', 'Rajasthan Royals'],
       [1, 'M', 'Pat Cummins', ..., '2 CR', '7.25 CR',
        'Kolkata Knight Riders'],
       ...,
       [57, 'UAL10', 'Arjun Tendulkar', ..., '20 L', '30 L',
        'Mumbai Indians'],
       [59, 'UAL12', 'Shubham Garhwal', ..., '20 L', '20 L',
        'Rajasthan Royals'],
       [60, 'UAL13', 'Anunay Singh', ..., '20 L', '20 L',
        'Rajasthan Royals']], dtype=object)

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
type(df.values)

numpy.ndarray

In [ ]:
df.value_counts

<bound method DataFrame.value_counts of      Set No. Set Name           Player       Country State Association  Age  \
0          1        M         R Ashwin         India              TNCA   35
1          1        M      Trent Boult   New Zealand               NaN   32
2          1        M      Pat Cummins     Australia               NaN   28
3          1        M   Shikhar Dhawan         India              DDCA   36
4          1        M   Faf Du Plessis  South Africa               NaN   37
..       ...      ...              ...           ...               ...  ...
179       53     UAL8       Ansh Patel         India               BCA   20
180       54     UFA8     Ashok Sharma         India               RCA   19
181       57    UAL10  Arjun Tendulkar         India               MCA   22
182       59    UAL12  Shubham Garhwal         India               RCA   26
183       60    UAL13     Anunay Singh         India              BICA   29

      Specialism Batting                   Bowling    IPL Previous IPLTeam(s)  \
0    ALL-ROUNDER     RHB        RIGHT ARM Off Spin  167.0  CSK, RSP, KXIP, DC
1         BOWLER     RHB      LEFT ARM Fast Medium   62.0     SRH, KKR, DD,MI
2    ALL-ROUNDER     RHB            RIGHT ARM Fast   37.0         DD, MI, KKR
3        BATSMAN     LHB                         -  192.0    DCH, MI, SRH, DC
4        BATSMAN     RHB        RIGHT ARM Leg Spin  100.0            RPS, CSK
..           ...     ...                       ...    ...                 ...
179  ALL-ROUNDER     RHB  LEFT ARM Slow Unorthodox    NaN                 NaN
180       BOWLER     RHB     RIGHT ARM Fast Medium    NaN                 NaN
181  ALL-ROUNDER     LHB      LEFT ARM Fast Medium    0.0                  MI
182  ALL-ROUNDER     LHB    LEFT ARM Slow Orthodox    NaN                 NaN
183  ALL-ROUNDER     RHB     RIGHT ARM Fast Medium    NaN                 NaN

    2021 Team     C/U/A Base Price Sold Price                New Franchise
0          DC    Capped       2 CR       5 CR             Rajasthan Royals
1          MI    Capped       2 CR       8 CR             Rajasthan Royals
2         KKR    Capped       2 CR    7.25 CR        Kolkata Knight Riders
3          DC    Capped       2 CR    8.25 CR                 Punjab Kings
4         CSK    Capped       2 CR       7 CR  Royal Challengers Bangalore
..        ...       ...        ...        ...                          ...
179       NaN  Uncapped       20 L       20 L                 Punjab Kings
180       NaN  Uncapped       20 L       55 L        Kolkata Knight Riders
181        MI  Uncapped       20 L       30 L               Mumbai Indians
182       NaN  Uncapped       20 L       20 L             Rajasthan Royals
183       NaN  Uncapped       20 L       20 L             Rajasthan Royals

[184 rows x 16 columns]>

In [ ]:
df.head(5)

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
0,1,M,R Ashwin,India,TNCA,35,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,167.0,"CSK, RSP, KXIP, DC",DC,Capped,2 CR,5 CR,Rajasthan Royals
1,1,M,Trent Boult,New Zealand,NaN,32,BOWLER,RHB,LEFT ARM Fast Medium,62.0,"SRH, KKR, DD,MI",MI,Capped,2 CR,8 CR,Rajasthan Royals
2,1,M,Pat Cummins,Australia,NaN,28,ALL-ROUNDER,RHB,RIGHT ARM Fast,37.0,"DD, MI, KKR",KKR,Capped,2 CR,7.25 CR,Kolkata Knight Riders
3,1,M,Shikhar Dhawan,India,DDCA,36,BATSMAN,LHB,-,192.0,"DCH, MI, SRH, DC",DC,Capped,2 CR,8.25 CR,Punjab Kings
4,1,M,Faf Du Plessis,South Africa,NaN,37,BATSMAN,RHB,RIGHT ARM Leg Spin,100.0,"RPS, CSK",CSK,Capped,2 CR,7 CR,Royal Challengers Bangalore

In [ ]:
df['Player']

0             R Ashwin
1          Trent Boult
2          Pat Cummins
3       Shikhar Dhawan
4       Faf Du Plessis
            ...
179         Ansh Patel
180       Ashok Sharma
181    Arjun Tendulkar
182    Shubham Garhwal
183       Anunay Singh
Name: Player, Length: 184, dtype: object

In [ ]:
df[['Player','Country']]

              Player       Country
0           R Ashwin         India
1        Trent Boult   New Zealand
2        Pat Cummins     Australia
3     Shikhar Dhawan         India
4     Faf Du Plessis  South Africa
..               ...           ...
179       Ansh Patel         India
180     Ashok Sharma         India
181  Arjun Tendulkar         India
182  Shubham Garhwal         India
183     Anunay Singh         India

[184 rows x 2 columns]

In [ ]:
df.index

RangeIndex(start=0, stop=184, step=1)

In [ ]:
df["Age"].sum()

4987

In [ ]:
df["Age"][0]

35

In [ ]:
df.loc[0,"Age"]

35

In [ ]:
df.iloc[0]

Set No.                                 1
Set Name                                M
Player                           R Ashwin
Country                             India
State Association                    TNCA
Age                                    35
Specialism                    ALL-ROUNDER
Batting                               RHB
Bowling                RIGHT ARM Off Spin
IPL                                 167.0
Previous IPLTeam(s)    CSK, RSP, KXIP, DC
2021 Team                              DC
C/U/A                              Capped
Base Price                           2 CR
Sold Price                           5 CR
New Franchise            Rajasthan Royals
Name: 0, dtype: object

In [ ]:
df.loc[0,"Player"]

'R Ashwin'

In [ ]:
df.loc[df["Age"]>35]

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
3,1,M,Shikhar Dhawan,India,DDCA,36,BATSMAN,LHB,-,192.0,"DCH, MI, SRH, DC",DC,Capped,2 CR,8.25 CR,Punjab Kings
4,1,M,Faf Du Plessis,South Africa,NaN,37,BATSMAN,RHB,RIGHT ARM Leg Spin,100.0,"RPS, CSK",CSK,Capped,2 CR,7 CR,Royal Challengers Bangalore
14,2,BA1,Robin Uthappa,India,KCA,36,BATSMAN,RHB,-,193.0,"MI, PWI, RCB, KKR, RR, CSK",CSK,Capped,2 CR,2 CR,Chennai Super Kings
15,3,AL1,Dwayne Bravo,West Indies,NaN,38,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,151.0,"MI, GL, CSK",CSK,Capped,2 CR,4.4 CR,Chennai Super Kings
25,4,WK1,Dinesh Karthik,India,TNCA,36,WICKETKEEPER,RHB,-,213.0,"KXIP, MI, DD, RCB, GL, KKR",KKR,Capped,2 CR,5.5 CR,Royal Challengers Bangalore
28,4,WK1,Ambati Rayudu,India,ACA,36,WICKETKEEPER,RHB,-,175.0,"MI, CSK",CSK,Capped,2 CR,6.75 CR,Chennai Super Kings

In [ ]:
df.loc[(df['Age']>30) & (df['Country']=='India')]

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
0,1,M,R Ashwin,India,TNCA,35,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,167.0,"CSK, RSP, KXIP, DC",DC,Capped,2 CR,5 CR,Rajasthan Royals
3,1,M,Shikhar Dhawan,India,DDCA,36,BATSMAN,LHB,-,192.0,"DCH, MI, SRH, DC",DC,Capped,2 CR,8.25 CR,Punjab Kings
7,1,M,Mohammad Shami,India,CAB,32,BOWLER,RHB,RIGHT ARM Fast,77.0,"DCH, KKR, DD, PBKS",PBKS,Capped,2 CR,6.25 CR,Gujarat Titans
12,2,BA1,Manish Pandey,India,KSCA,32,BATSMAN,RHB,RIGHT ARM Off Spin,154.0,"MI, RCB, PWI, KKR, SRH",SRH,Capped,1 CR,4.6 CR,Lucknow Super Giants
14,2,BA1,Robin Uthappa,India,KCA,36,BATSMAN,RHB,-,193.0,"MI, PWI, RCB, KKR, RR, CSK",CSK,Capped,2 CR,2 CR,Chennai Super Kings
19,3,AL1,Krunal Pandya,India,BCA,31,ALL-ROUNDER,LHB,LEFT ARM Slow Orthodox,84.0,MI,MI,Capped,2 CR,8.25 CR,Lucknow Super Giants
20,3,AL1,Harshal Patel,India,HCA,31,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,63.0,"DC, RCB",RCB,Capped,2 CR,10.75 CR,Royal Challengers Bangalore
25,4,WK1,Dinesh Karthik,India,TNCA,36,WICKETKEEPER,RHB,-,213.0,"KXIP, MI, DD, RCB, GL, KKR",KKR,Capped,2 CR,5.5 CR,Royal Challengers Bangalore
28,4,WK1,Ambati Rayudu,India,ACA,36,WICKETKEEPER,RHB,-,175.0,"MI, CSK",CSK,Capped,2 CR,6.75 CR,Chennai Super Kings
34,5,FA1,Bhuvneshwar Kumar,India,UPCA,32,BOWLER,RHB,RIGHT ARM Fast Medium,132.0,"PWI, SRH",SRH,Capped,2 CR,4.2 CR,Sunrisers Hyderabad
38,5,FA1,Umesh Yadav,India,VCA,34,BOWLER,RHB,RIGHT ARM Fast,121.0,"DD, KKR,RCB,DC",DC,Capped,2 CR,2 CR,Kolkata Knight Riders
39,6,SP1,Yuzvendra Chahal,India,HCA,31,BOWLER,RHB,RIGHT ARM Leg Spin,114.0,"MI,RCB",RCB,Capped,2 CR,6.5 CR,Rajasthan Royals
47,7,UBA1,Rahul Tripathi,India,MACA,31,BATSMAN,RHB,RIGHT ARM Medium,62.0,"RPS, RR, KKR",KKR,Uncapped,40 L,8.5 CR,Sunrisers Hyderabad
58,9,UWK1,Sheldon Jackson,India,SCA,35,WICKETKEEPER,RHB,-,4.0,KKR,KKR,Uncapped,30 L,60 L,Kolkata Knight Riders
70,11,USP1,Murugan Ashwin,India,TNCA,31,BOWLER,RHB,RIGHT ARM Leg Spin,34.0,"RPS, DD, RCB, PBKS",PBKS,Uncapped,20 L,1.6 CR,Mumbai Indians
74,12,BA2,Ajinkya Rahane,India,MCA,33,BATSMAN,RHB,-,151.0,"MI, RPS, RR, DC",DC,Capped,1 CR,1 CR,Kolkata Knight Riders
78,13,AL2,K. Gowtham,India,KSCA,33,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,24.0,"MI, RR, KXIP, CSK",CSK,Capped,50 L,90 L,Lucknow Super Giants
83,13,AL2,Vijay Shankar,India,TNCA,31,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,47.0,"CSK, DD, SRH",SRH,Capped,50 L,1.40 CR,Gujarat Titans
85,13,AL2,Jayant Yadav,India,HCA,32,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,19.0,"DD, MI",MI,Capped,1 CR,1.70 CR,Gujarat Titans
93,15,SP2,Shahbaz Nadeem,India,JSCA,32,BOWLER,RHB,LEFT ARM Slow Orthodox,72.0,"DD, SRH",SRH,Capped,50 L,50 L,Lucknow Super Giants
94,15,SP2,Karn Sharma,India,RSPB,34,BOWLER,LHB,RIGHT ARM Leg Spin,68.0,"RCB, SRH, MI, CSK",CSK,Capped,50 L,50 L,Royal Challengers Bangalore
117,20,AL3,Rishi Dhawan,India,HPCA,32,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,26.0,"MI, KXIP, KKR",NaN,Capped,50 L,55 L,Punjab Kings
129,22,FA3,Siddharth Kaul,India,PCA,31,BOWLER,RHB,RIGHT ARM Fast Medium,54.0,"KKR, DD, SRH",SRH,Capped,75 L,75 L,Royal Challengers Bangalore
151,30,AL4,Gurkeerat Singh,India,PCA,31,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,41.0,NaN,KKR,Capped,50 L,50 L,Gujarat Titan
164,39,FA5,Varun Aaron,India,JSCA,32,BOWLER,RHB,RIGHT ARM Fast,50.0,"DD, RCB,KXIP, RR",NaN,Capped,50 L,50 L,Gujarat Titans
168,41,UAL5,Pradeep Sangwan,India,DDCA,31,ALL-ROUNDER,RHB,LEFT ARM Fast,39.0,"DD, GL, MI",NaN,Uncapped,20 L,20 L,Gujarat Titans
176,52,UFA7,Baltej Dhanda,India,PCA,31,BOWLER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20 L,20 L,Punjab Kings

In [ ]:
df.loc[(df['Country']=='India') & (df['Age']>30)]

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
0,1,M,R Ashwin,India,TNCA,35,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,167.0,"CSK, RSP, KXIP, DC",DC,Capped,2 CR,5 CR,Rajasthan Royals
3,1,M,Shikhar Dhawan,India,DDCA,36,BATSMAN,LHB,-,192.0,"DCH, MI, SRH, DC",DC,Capped,2 CR,8.25 CR,Punjab Kings
7,1,M,Mohammad Shami,India,CAB,32,BOWLER,RHB,RIGHT ARM Fast,77.0,"DCH, KKR, DD, PBKS",PBKS,Capped,2 CR,6.25 CR,Gujarat Titans
12,2,BA1,Manish Pandey,India,KSCA,32,BATSMAN,RHB,RIGHT ARM Off Spin,154.0,"MI, RCB, PWI, KKR, SRH",SRH,Capped,1 CR,4.6 CR,Lucknow Super Giants
14,2,BA1,Robin Uthappa,India,KCA,36,BATSMAN,RHB,-,193.0,"MI, PWI, RCB, KKR, RR, CSK",CSK,Capped,2 CR,2 CR,Chennai Super Kings
19,3,AL1,Krunal Pandya,India,BCA,31,ALL-ROUNDER,LHB,LEFT ARM Slow Orthodox,84.0,MI,MI,Capped,2 CR,8.25 CR,Lucknow Super Giants
20,3,AL1,Harshal Patel,India,HCA,31,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,63.0,"DC, RCB",RCB,Capped,2 CR,10.75 CR,Royal Challengers Bangalore
25,4,WK1,Dinesh Karthik,India,TNCA,36,WICKETKEEPER,RHB,-,213.0,"KXIP, MI, DD, RCB, GL, KKR",KKR,Capped,2 CR,5.5 CR,Royal Challengers Bangalore
28,4,WK1,Ambati Rayudu,India,ACA,36,WICKETKEEPER,RHB,-,175.0,"MI, CSK",CSK,Capped,2 CR,6.75 CR,Chennai Super Kings
34,5,FA1,Bhuvneshwar Kumar,India,UPCA,32,BOWLER,RHB,RIGHT ARM Fast Medium,132.0,"PWI, SRH",SRH,Capped,2 CR,4.2 CR,Sunrisers Hyderabad
38,5,FA1,Umesh Yadav,India,VCA,34,BOWLER,RHB,RIGHT ARM Fast,121.0,"DD, KKR,RCB,DC",DC,Capped,2 CR,2 CR,Kolkata Knight Riders
39,6,SP1,Yuzvendra Chahal,India,HCA,31,BOWLER,RHB,RIGHT ARM Leg Spin,114.0,"MI,RCB",RCB,Capped,2 CR,6.5 CR,Rajasthan Royals
47,7,UBA1,Rahul Tripathi,India,MACA,31,BATSMAN,RHB,RIGHT ARM Medium,62.0,"RPS, RR, KKR",KKR,Uncapped,40 L,8.5 CR,Sunrisers Hyderabad
58,9,UWK1,Sheldon Jackson,India,SCA,35,WICKETKEEPER,RHB,-,4.0,KKR,KKR,Uncapped,30 L,60 L,Kolkata Knight Riders
70,11,USP1,Murugan Ashwin,India,TNCA,31,BOWLER,RHB,RIGHT ARM Leg Spin,34.0,"RPS, DD, RCB, PBKS",PBKS,Uncapped,20 L,1.6 CR,Mumbai Indians
74,12,BA2,Ajinkya Rahane,India,MCA,33,BATSMAN,RHB,-,151.0,"MI, RPS, RR, DC",DC,Capped,1 CR,1 CR,Kolkata Knight Riders
78,13,AL2,K. Gowtham,India,KSCA,33,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,24.0,"MI, RR, KXIP, CSK",CSK,Capped,50 L,90 L,Lucknow Super Giants
83,13,AL2,Vijay Shankar,India,TNCA,31,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,47.0,"CSK, DD, SRH",SRH,Capped,50 L,1.40 CR,Gujarat Titans
85,13,AL2,Jayant Yadav,India,HCA,32,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,19.0,"DD, MI",MI,Capped,1 CR,1.70 CR,Gujarat Titans
93,15,SP2,Shahbaz Nadeem,India,JSCA,32,BOWLER,RHB,LEFT ARM Slow Orthodox,72.0,"DD, SRH",SRH,Capped,50 L,50 L,Lucknow Super Giants
94,15,SP2,Karn Sharma,India,RSPB,34,BOWLER,LHB,RIGHT ARM Leg Spin,68.0,"RCB, SRH, MI, CSK",CSK,Capped,50 L,50 L,Royal Challengers Bangalore
117,20,AL3,Rishi Dhawan,India,HPCA,32,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,26.0,"MI, KXIP, KKR",NaN,Capped,50 L,55 L,Punjab Kings
129,22,FA3,Siddharth Kaul,India,PCA,31,BOWLER,RHB,RIGHT ARM Fast Medium,54.0,"KKR, DD, SRH",SRH,Capped,75 L,75 L,Royal Challengers Bangalore
151,30,AL4,Gurkeerat Singh,India,PCA,31,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,41.0,NaN,KKR,Capped,50 L,50 L,Gujarat Titan
164,39,FA5,Varun Aaron,India,JSCA,32,BOWLER,RHB,RIGHT ARM Fast,50.0,"DD, RCB,KXIP, RR",NaN,Capped,50 L,50 L,Gujarat Titans
168,41,UAL5,Pradeep Sangwan,India,DDCA,31,ALL-ROUNDER,RHB,LEFT ARM Fast,39.0,"DD, GL, MI",NaN,Uncapped,20 L,20 L,Gujarat Titans
176,52,UFA7,Baltej Dhanda,India,PCA,31,BOWLER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20 L,20 L,Punjab Kings

In [ ]:
df.loc[df["Country"]=="India"]

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
0,1,M,R Ashwin,India,TNCA,35,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,167.0,"CSK, RSP, KXIP, DC",DC,Capped,2 CR,5 CR,Rajasthan Royals
3,1,M,Shikhar Dhawan,India,DDCA,36,BATSMAN,LHB,-,192.0,"DCH, MI, SRH, DC",DC,Capped,2 CR,8.25 CR,Punjab Kings
5,1,M,Shreyas Iyer,India,MCA,27,BATSMAN,RHB,RIGHT ARM Leg Spin,87.0,DC,DC,Capped,2 CR,12.25 CR,Kolkata Knight Riders
7,1,M,Mohammad Shami,India,CAB,32,BOWLER,RHB,RIGHT ARM Fast,77.0,"DCH, KKR, DD, PBKS",PBKS,Capped,2 CR,6.25 CR,Gujarat Titans
11,2,BA1,Devdutt Padikkal,India,KSCA,21,BATSMAN,LHB,RIGHT ARM Off Spin,29.0,RCB,RCB,Capped,2 CR,7.75 CR,Rajasthan Royals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,53,UAL8,Ansh Patel,India,BCA,20,ALL-ROUNDER,RHB,LEFT ARM Slow Unorthodox,NaN,NaN,NaN,Uncapped,20 L,20 L,Punjab Kings
180,54,UFA8,Ashok Sharma,India,RCA,19,BOWLER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20 L,55 L,Kolkata Knight Riders
181,57,UAL10,Arjun Tendulkar,India,MCA,22,ALL-ROUNDER,LHB,LEFT ARM Fast Medium,0.0,MI,MI,Uncapped,20 L,30 L,Mumbai Indians
182,59,UAL12,Shubham Garhwal,India,RCA,26,ALL-ROUNDER,LHB,LEFT ARM Slow Orthodox,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals
183,60,UAL13,Anunay Singh,India,BICA,29,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals

In [ ]:
df.isnull()

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,False,False,False,False,False,False,False,False,False,True,True,True,False,False,False,False
180,False,False,False,False,False,False,False,False,False,True,True,True,False,False,False,False
181,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
182,False,False,False,False,False,False,False,False,False,True,True,True,False,False,False,False
183,False,False,False,False,False,False,False,False,False,True,True,True,False,False,False,False

In [ ]:
df.fillna(0)

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
0,1,M,R Ashwin,India,TNCA,35,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,167.0,"CSK, RSP, KXIP, DC",DC,Capped,2 CR,5 CR,Rajasthan Royals
1,1,M,Trent Boult,New Zealand,0,32,BOWLER,RHB,LEFT ARM Fast Medium,62.0,"SRH, KKR, DD,MI",MI,Capped,2 CR,8 CR,Rajasthan Royals
2,1,M,Pat Cummins,Australia,0,28,ALL-ROUNDER,RHB,RIGHT ARM Fast,37.0,"DD, MI, KKR",KKR,Capped,2 CR,7.25 CR,Kolkata Knight Riders
3,1,M,Shikhar Dhawan,India,DDCA,36,BATSMAN,LHB,-,192.0,"DCH, MI, SRH, DC",DC,Capped,2 CR,8.25 CR,Punjab Kings
4,1,M,Faf Du Plessis,South Africa,0,37,BATSMAN,RHB,RIGHT ARM Leg Spin,100.0,"RPS, CSK",CSK,Capped,2 CR,7 CR,Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,53,UAL8,Ansh Patel,India,BCA,20,ALL-ROUNDER,RHB,LEFT ARM Slow Unorthodox,0.0,0,0,Uncapped,20 L,20 L,Punjab Kings
180,54,UFA8,Ashok Sharma,India,RCA,19,BOWLER,RHB,RIGHT ARM Fast Medium,0.0,0,0,Uncapped,20 L,55 L,Kolkata Knight Riders
181,57,UAL10,Arjun Tendulkar,India,MCA,22,ALL-ROUNDER,LHB,LEFT ARM Fast Medium,0.0,MI,MI,Uncapped,20 L,30 L,Mumbai Indians
182,59,UAL12,Shubham Garhwal,India,RCA,26,ALL-ROUNDER,LHB,LEFT ARM Slow Orthodox,0.0,0,0,Uncapped,20 L,20 L,Rajasthan Royals
183,60,UAL13,Anunay Singh,India,BICA,29,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,0.0,0,0,Uncapped,20 L,20 L,Rajasthan Royals

In [ ]:
df.describe()

          Set No.         Age         IPL
count  184.000000  184.000000  137.000000
mean    17.989130   27.103261   36.897810
std     14.200742    4.428570   46.902635
min      1.000000   17.000000    0.000000
25%      7.000000   24.000000    3.000000
50%     14.500000   27.000000   21.000000
75%     25.000000   30.250000   50.000000
max     60.000000   38.000000  213.000000

In [ ]:
df.dropna()

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
0,1,M,R Ashwin,India,TNCA,35,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,167.0,"CSK, RSP, KXIP, DC",DC,Capped,2 CR,5 CR,Rajasthan Royals
3,1,M,Shikhar Dhawan,India,DDCA,36,BATSMAN,LHB,-,192.0,"DCH, MI, SRH, DC",DC,Capped,2 CR,8.25 CR,Punjab Kings
5,1,M,Shreyas Iyer,India,MCA,27,BATSMAN,RHB,RIGHT ARM Leg Spin,87.0,DC,DC,Capped,2 CR,12.25 CR,Kolkata Knight Riders
7,1,M,Mohammad Shami,India,CAB,32,BOWLER,RHB,RIGHT ARM Fast,77.0,"DCH, KKR, DD, PBKS",PBKS,Capped,2 CR,6.25 CR,Gujarat Titans
11,2,BA1,Devdutt Padikkal,India,KSCA,21,BATSMAN,LHB,RIGHT ARM Off Spin,29.0,RCB,RCB,Capped,2 CR,7.75 CR,Rajasthan Royals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,25,UAL3,Pravin Dubey,India,KSCA,28,ALL-ROUNDER,RHB,RIGHT ARM Leg Spin,3.0,"RCB, DC",DC,Uncapped,20 L,50 L,Delhi Capitals
137,25,UAL3,Suyash Prabhudessai,India,GCA,24,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,0.0,RCB,RCB,Uncapped,20 L,30 L,Royal Challengers Bangalore
142,27,UFA3,Vaibhav Arora,India,HPCA,24,BOWLER,RHB,RIGHT ARM Fast Medium,0.0,KKR,KKR,Uncapped,20 L,2 CR,Punjab Kings
145,27,UFA3,Mohsin Khan,India,UPCA,23,BOWLER,LHB,LEFT ARM Fast Medium,0.0,MI,MI,Uncapped,20 L,20 L,Luknow Super Giants
181,57,UAL10,Arjun Tendulkar,India,MCA,22,ALL-ROUNDER,LHB,LEFT ARM Fast Medium,0.0,MI,MI,Uncapped,20 L,30 L,Mumbai Indians

In [ ]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
179    False
180    False
181    False
182    False
183    False
Length: 184, dtype: bool

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
0,1,M,R Ashwin,India,TNCA,35,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,167.0,"CSK, RSP, KXIP, DC",DC,Capped,2 CR,5 CR,Rajasthan Royals
1,1,M,Trent Boult,New Zealand,NaN,32,BOWLER,RHB,LEFT ARM Fast Medium,62.0,"SRH, KKR, DD,MI",MI,Capped,2 CR,8 CR,Rajasthan Royals
2,1,M,Pat Cummins,Australia,NaN,28,ALL-ROUNDER,RHB,RIGHT ARM Fast,37.0,"DD, MI, KKR",KKR,Capped,2 CR,7.25 CR,Kolkata Knight Riders
3,1,M,Shikhar Dhawan,India,DDCA,36,BATSMAN,LHB,-,192.0,"DCH, MI, SRH, DC",DC,Capped,2 CR,8.25 CR,Punjab Kings
4,1,M,Faf Du Plessis,South Africa,NaN,37,BATSMAN,RHB,RIGHT ARM Leg Spin,100.0,"RPS, CSK",CSK,Capped,2 CR,7 CR,Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,53,UAL8,Ansh Patel,India,BCA,20,ALL-ROUNDER,RHB,LEFT ARM Slow Unorthodox,NaN,NaN,NaN,Uncapped,20 L,20 L,Punjab Kings
180,54,UFA8,Ashok Sharma,India,RCA,19,BOWLER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20 L,55 L,Kolkata Knight Riders
181,57,UAL10,Arjun Tendulkar,India,MCA,22,ALL-ROUNDER,LHB,LEFT ARM Fast Medium,0.0,MI,MI,Uncapped,20 L,30 L,Mumbai Indians
182,59,UAL12,Shubham Garhwal,India,RCA,26,ALL-ROUNDER,LHB,LEFT ARM Slow Orthodox,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals
183,60,UAL13,Anunay Singh,India,BICA,29,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals

In [ ]:
  df.tail(-4)

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
4,1,M,Faf Du Plessis,South Africa,NaN,37,BATSMAN,RHB,RIGHT ARM Leg Spin,100.0,"RPS, CSK",CSK,Capped,2 CR,7 CR,Royal Challengers Bangalore
5,1,M,Shreyas Iyer,India,MCA,27,BATSMAN,RHB,RIGHT ARM Leg Spin,87.0,DC,DC,Capped,2 CR,12.25 CR,Kolkata Knight Riders
6,1,M,Kagiso Rabada,South Africa,NaN,26,BOWLER,LHB,RIGHT ARM Fast,50.0,DC,DC,Capped,2 CR,9.25 CR,Punjab Kings
7,1,M,Mohammad Shami,India,CAB,32,BOWLER,RHB,RIGHT ARM Fast,77.0,"DCH, KKR, DD, PBKS",PBKS,Capped,2 CR,6.25 CR,Gujarat Titans
8,1,M,David Warner,Australia,NaN,35,BATSMAN,LHB,-,150.0,"DD, SRH",SRH,Capped,2 CR,6.25 CR,Delhi Capitals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,53,UAL8,Ansh Patel,India,BCA,20,ALL-ROUNDER,RHB,LEFT ARM Slow Unorthodox,NaN,NaN,NaN,Uncapped,20 L,20 L,Punjab Kings
180,54,UFA8,Ashok Sharma,India,RCA,19,BOWLER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20 L,55 L,Kolkata Knight Riders
181,57,UAL10,Arjun Tendulkar,India,MCA,22,ALL-ROUNDER,LHB,LEFT ARM Fast Medium,0.0,MI,MI,Uncapped,20 L,30 L,Mumbai Indians
182,59,UAL12,Shubham Garhwal,India,RCA,26,ALL-ROUNDER,LHB,LEFT ARM Slow Orthodox,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals
183,60,UAL13,Anunay Singh,India,BICA,29,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals

In [ ]:
df.loc[(df['Specialism']=="BATSMAN") & (df['Batting']=='LHB')]

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
3,1,M,Shikhar Dhawan,India,DDCA,36,BATSMAN,LHB,-,192.0,"DCH, MI, SRH, DC",DC,Capped,2 CR,8.25 CR,Punjab Kings
8,1,M,David Warner,Australia,NaN,35,BATSMAN,LHB,-,150.0,"DD, SRH",SRH,Capped,2 CR,6.25 CR,Delhi Capitals
9,2,BA1,Shimron Hetmyer,West Indies,NaN,25,BATSMAN,LHB,RIGHT ARM Leg Spin,31.0,"RCB, DC",DC,Capped,1.5 CR,8.5 CR,Rajasthan Royals
10,2,BA1,David Miller,South Africa,NaN,32,BATSMAN,LHB,-,89.0,"KXIP, RR",RR,Capped,1 CR,3 CR,Gujarat Titans
11,2,BA1,Devdutt Padikkal,India,KSCA,21,BATSMAN,LHB,RIGHT ARM Off Spin,29.0,RCB,RCB,Capped,2 CR,7.75 CR,Rajasthan Royals
96,16,UBA2,Rinku Singh,India,UPCA,24,BATSMAN,LHB,RIGHT ARM Off Spin,11.0,KKR,NaN,Uncapped,20 L,55 L,Kolkata Knight Riders
111,19,BA3,Devon Conway,New Zealand,NaN,30,BATSMAN,LHB,RIGHT ARM Medium,NaN,NaN,NaN,Capped,1 CR,1 CR,Chennai Super Kings
113,19,BA3,Evin Lewis,West Indies,NaN,30,BATSMAN,LHB,-,21.0,"MI, RR",RR,Capped,2 CR,2 CR,Lucknow Super Giants
156,32,UBA4,Rahul Buddhi,India,HYCA,24,BATSMAN,LHB,RIGHT ARM Leg Spin,NaN,NaN,NaN,Uncapped,20 L,20 L,Mumbai Indians
169,47,UBA6,Ramesh Kumar,India,PCA,23,BATSMAN,LHB,-,NaN,NaN,NaN,Uncapped,20 L,20 L,Kolkata Knight Riders
170,47,UBA6,Pratham Singh,India,RSPB,29,BATSMAN,LHB,RIGHT ARM Off Spin,0.0,GL,NaN,Uncapped,20 L,20 L,Kolkata Knight Riders

In [ ]:
 df.loc[[0,1]]

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
0,1,M,R Ashwin,India,TNCA,35,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,167.0,"CSK, RSP, KXIP, DC",DC,Capped,2 CR,5 CR,Rajasthan Royals
1,1,M,Trent Boult,New Zealand,NaN,32,BOWLER,RHB,LEFT ARM Fast Medium,62.0,"SRH, KKR, DD,MI",MI,Capped,2 CR,8 CR,Rajasthan Royals

In [ ]:
df.loc[0]

Set No.                                 1
Set Name                                M
Player                           R Ashwin
Country                             India
State Association                    TNCA
Age                                    35
Specialism                    ALL-ROUNDER
Batting                               RHB
Bowling                RIGHT ARM Off Spin
IPL                                 167.0
Previous IPLTeam(s)    CSK, RSP, KXIP, DC
2021 Team                              DC
C/U/A                              Capped
Base Price                           2 CR
Sold Price                           5 CR
New Franchise            Rajasthan Royals
Name: 0, dtype: object

In [ ]:
df

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
0,1,M,R Ashwin,India,TNCA,35,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,167.0,"CSK, RSP, KXIP, DC",DC,Capped,2 CR,5 CR,Rajasthan Royals
1,1,M,Trent Boult,New Zealand,NaN,32,BOWLER,RHB,LEFT ARM Fast Medium,62.0,"SRH, KKR, DD,MI",MI,Capped,2 CR,8 CR,Rajasthan Royals
2,1,M,Pat Cummins,Australia,NaN,28,ALL-ROUNDER,RHB,RIGHT ARM Fast,37.0,"DD, MI, KKR",KKR,Capped,2 CR,7.25 CR,Kolkata Knight Riders
3,1,M,Shikhar Dhawan,India,DDCA,36,BATSMAN,LHB,-,192.0,"DCH, MI, SRH, DC",DC,Capped,2 CR,8.25 CR,Punjab Kings
4,1,M,Faf Du Plessis,South Africa,NaN,37,BATSMAN,RHB,RIGHT ARM Leg Spin,100.0,"RPS, CSK",CSK,Capped,2 CR,7 CR,Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,53,UAL8,Ansh Patel,India,BCA,20,ALL-ROUNDER,RHB,LEFT ARM Slow Unorthodox,NaN,NaN,NaN,Uncapped,20 L,20 L,Punjab Kings
180,54,UFA8,Ashok Sharma,India,RCA,19,BOWLER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20 L,55 L,Kolkata Knight Riders
181,57,UAL10,Arjun Tendulkar,India,MCA,22,ALL-ROUNDER,LHB,LEFT ARM Fast Medium,0.0,MI,MI,Uncapped,20 L,30 L,Mumbai Indians
182,59,UAL12,Shubham Garhwal,India,RCA,26,ALL-ROUNDER,LHB,LEFT ARM Slow Orthodox,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals
183,60,UAL13,Anunay Singh,India,BICA,29,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals

In [ ]:
df.loc[0]

Set No.                                 1
Set Name                                M
Player                           R Ashwin
Country                             India
State Association                    TNCA
Age                                    35
Specialism                    ALL-ROUNDER
Batting                               RHB
Bowling                RIGHT ARM Off Spin
IPL                                 167.0
Previous IPLTeam(s)    CSK, RSP, KXIP, DC
2021 Team                              DC
C/U/A                              Capped
Base Price                           2 CR
Sold Price                           5 CR
New Franchise            Rajasthan Royals
Name: 0, dtype: object

In [ ]:
df=pd.DataFrame(data=df,index=['a','b','c'])

In [ ]:
df

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
c,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df[df['New Franchise']=='Rajasthan Royals']

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
0,1,M,R Ashwin,India,TNCA,35,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,167.0,"CSK, RSP, KXIP, DC",DC,Capped,2 CR,5 CR,Rajasthan Royals
1,1,M,Trent Boult,New Zealand,NaN,32,BOWLER,RHB,LEFT ARM Fast Medium,62.0,"SRH, KKR, DD,MI",MI,Capped,2 CR,8 CR,Rajasthan Royals
9,2,BA1,Shimron Hetmyer,West Indies,NaN,25,BATSMAN,LHB,RIGHT ARM Leg Spin,31.0,"RCB, DC",DC,Capped,1.5 CR,8.5 CR,Rajasthan Royals
11,2,BA1,Devdutt Padikkal,India,KSCA,21,BATSMAN,LHB,RIGHT ARM Off Spin,29.0,RCB,RCB,Capped,2 CR,7.75 CR,Rajasthan Royals
33,5,FA1,Prasidh Krishna,India,KSCA,26,BOWLER,RHB,RIGHT ARM Fast,34.0,KKR,KKR,Capped,1 CR,10 CR,Rajasthan Royals
39,6,SP1,Yuzvendra Chahal,India,HCA,31,BOWLER,RHB,RIGHT ARM Leg Spin,114.0,"MI,RCB",RCB,Capped,2 CR,6.5 CR,Rajasthan Royals
55,8,UAL1,Riyan Parag,India,ASCA,20,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,30.0,RR,RR,Uncapped,30 L,3.8 CR,Rajasthan Royals
82,13,AL2,James Neesham,New Zealand,NaN,31,ALL-ROUNDER,LHB,RIGHT ARM Fast Medium,12.0,"DD, KXIP, MI",MI,Capped,1.50 CR,1.50 CR,Rajasthan Royals
87,14,FA2,Nathan Coulter-Nile,Australia,NaN,34,BOWLER,RHB,RIGHT ARM Fast Medium,38.0,"DD, KKR, RCB, MI",MI,Capped,2 CR,2 CR,Rajasthan Royals
88,14,FA2,Navdeep Saini,India,DDCA,29,BOWLER,RHB,RIGHT ARM Fast,28.0,"DD, RCB",RCB,Capped,75 L,2.60 CR,Rajasthan Royals
108,18,UFA2,Kuldeep Sen,India,MPCA,25,BOWLER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals
114,19,BA3,Karun Nair,India,KSCA,30,BATSMAN,RHB,RIGHT ARM Off Spin,73.0,"RCB, RR, DD, KXIP, KKR",KKR,Capped,50 L,1.40 CR,Rajasthan Royals
118,20,AL3,Daryl Mitchell,New Zealand,NaN,30,ALL-ROUNDER,RHB,RIGHT ARM Medium,NaN,NaN,NaN,Capped,75 L,75 L,Rajasthan Royals
130,22,FA3,Obed McCoy,West Indies,NaN,25,BOWLER,LHB,LEFT ARM Fast,NaN,NaN,NaN,Capped,75 L,75 L,Rajasthan Royals
139,26,UWK2,Dhruv Jurel,India,UPCA,21,WICKETKEEPER,RHB,-,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals
148,28,USP2,Tejas Baroka,India,DDCA,26,BOWLER,RHB,RIGHT ARM Leg Spin,1.0,GL,NaN,Uncapped,20 L,20 L,Rajasthan Royals
161,35,UFA4,Kuldip Yadav,India,DDCA,25,BOWLER,LHB,LEFT ARM Fast,1.0,NaN,RR,Uncapped,20 L,20 L,Rajasthan Royals
182,59,UAL12,Shubham Garhwal,India,RCA,26,ALL-ROUNDER,LHB,LEFT ARM Slow Orthodox,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals
183,60,UAL13,Anunay Singh,India,BICA,29,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals

In [ ]:
df

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
c,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.loc[(df['New Franchise']=='Rajasthan Royals') & (df['IPL']==38)]

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
87,14,FA2,Nathan Coulter-Nile,Australia,NaN,34,BOWLER,RHB,RIGHT ARM Fast Medium,38.0,"DD, KKR, RCB, MI",MI,Capped,2 CR,2 CR,Rajasthan Royals

In [ ]:
df

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
0,1,M,R Ashwin,India,TNCA,35,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,167.0,"CSK, RSP, KXIP, DC",DC,Capped,2 CR,5 CR,Rajasthan Royals
1,1,M,Trent Boult,New Zealand,NaN,32,BOWLER,RHB,LEFT ARM Fast Medium,62.0,"SRH, KKR, DD,MI",MI,Capped,2 CR,8 CR,Rajasthan Royals
2,1,M,Pat Cummins,Australia,NaN,28,ALL-ROUNDER,RHB,RIGHT ARM Fast,37.0,"DD, MI, KKR",KKR,Capped,2 CR,7.25 CR,Kolkata Knight Riders
3,1,M,Shikhar Dhawan,India,DDCA,36,BATSMAN,LHB,-,192.0,"DCH, MI, SRH, DC",DC,Capped,2 CR,8.25 CR,Punjab Kings
4,1,M,Faf Du Plessis,South Africa,NaN,37,BATSMAN,RHB,RIGHT ARM Leg Spin,100.0,"RPS, CSK",CSK,Capped,2 CR,7 CR,Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,53,UAL8,Ansh Patel,India,BCA,20,ALL-ROUNDER,RHB,LEFT ARM Slow Unorthodox,NaN,NaN,NaN,Uncapped,20 L,20 L,Punjab Kings
180,54,UFA8,Ashok Sharma,India,RCA,19,BOWLER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20 L,55 L,Kolkata Knight Riders
181,57,UAL10,Arjun Tendulkar,India,MCA,22,ALL-ROUNDER,LHB,LEFT ARM Fast Medium,0.0,MI,MI,Uncapped,20 L,30 L,Mumbai Indians
182,59,UAL12,Shubham Garhwal,India,RCA,26,ALL-ROUNDER,LHB,LEFT ARM Slow Orthodox,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals
183,60,UAL13,Anunay Singh,India,BICA,29,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals

In [ ]:
df.loc[(df['New Franchise']=='Rajasthan Royals') & (df['Sold Price']=='20 L')]

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
108,18,UFA2,Kuldeep Sen,India,MPCA,25,BOWLER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals
139,26,UWK2,Dhruv Jurel,India,UPCA,21,WICKETKEEPER,RHB,-,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals
148,28,USP2,Tejas Baroka,India,DDCA,26,BOWLER,RHB,RIGHT ARM Leg Spin,1.0,GL,NaN,Uncapped,20 L,20 L,Rajasthan Royals
161,35,UFA4,Kuldip Yadav,India,DDCA,25,BOWLER,LHB,LEFT ARM Fast,1.0,NaN,RR,Uncapped,20 L,20 L,Rajasthan Royals
182,59,UAL12,Shubham Garhwal,India,RCA,26,ALL-ROUNDER,LHB,LEFT ARM Slow Orthodox,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals
183,60,UAL13,Anunay Singh,India,BICA,29,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20 L,20 L,Rajasthan Royals

In [ ]:
#base price 20 L and age is above 30 and Team mi
df.loc[(df['Base Price']=='20 L')& (df['Age']<30) &(df['New Franchise']=='Mumbai Indians')]

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
42,7,UBA1,Dewald Brevis,South Africa,NaN,18,BATSMAN,RHB,RIGHT ARM Leg Spin,NaN,NaN,NaN,Uncapped,20 L,3 CR,Mumbai Indians
46,7,UBA1,Anmolpreet Singh,India,PCA,24,BATSMAN,RHB,RIGHT ARM Off Spin,1.0,MI,MI,Uncapped,20 L,20 L,Mumbai Indians
106,17,UAL2,Sanjay Yadav,India,TNCA,26,ALL-ROUNDER,LHB,LEFT ARM Slow Orthodox,0.0,"KKR, SRH",NaN,Uncapped,20 L,50 L,Mumbai Indians
138,25,UAL3,Ramandeep Singh,India,PCA,24,ALL-ROUNDER,RHB,RIGHT ARM Fast,NaN,NaN,NaN,Uncapped,20 L,20 L,Mumbai Indians
140,26,UWK2,Aryan Juyal,India,UPCA,20,WICKETKEEPER,RHB,-,NaN,NaN,NaN,Uncapped,20 L,20 L,Mumbai Indians
156,32,UBA4,Rahul Buddhi,India,HYCA,24,BATSMAN,LHB,RIGHT ARM Leg Spin,NaN,NaN,NaN,Uncapped,20 L,20 L,Mumbai Indians
172,48,UAL6,Hrithik Shokeen,India,DDCA,21,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,NaN,NaN,NaN,Uncapped,20 L,20 L,Mumbai Indians
181,57,UAL10,Arjun Tendulkar,India,MCA,22,ALL-ROUNDER,LHB,LEFT ARM Fast Medium,0.0,MI,MI,Uncapped,20 L,30 L,Mumbai Indians

In [ ]:
df.iloc[[0,5],[0,2]]

   Set No.        Player
0        1      R Ashwin
5        1  Shreyas Iyer

In [ ]:
df['New Franchise'].value_counts()

Kolkata Knight Riders          20
Punjab Kings                   20
Rajasthan Royals               19
Royal Challengers Bangalore    19
Sunrisers Hyderabad            19
Mumbai Indians                 19
Delhi Capitals                 18
Chennai Super Kings            17
Gujarat Titans                 16
Lucknow Super Giants           15
Luknow Super Giants             1
Gujarat Titan                   1
Name: New Franchise, dtype: int64

In [ ]:
for index,row in df.iterrows():
  print(index,row)

0 Set No.                                 1
Set Name                                M
Player                           R Ashwin
Country                             India
State Association                    TNCA
Age                                    35
Specialism                    ALL-ROUNDER
Batting                               RHB
Bowling                RIGHT ARM Off Spin
IPL                                 167.0
Previous IPLTeam(s)    CSK, RSP, KXIP, DC
2021 Team                              DC
C/U/A                              Capped
Base Price                           2 CR
Sold Price                           5 CR
New Franchise            Rajasthan Royals
Name: 0, dtype: object
1 Set No.                                   1
Set Name                                  M
Player                          Trent Boult
Country                         New Zealand
State Association                       NaN
Age                                      32
Specialism                           BOWLER
Batting                                 RHB
Bowling                LEFT ARM Fast Medium
IPL                                    62.0
Previous IPLTeam(s)         SRH, KKR, DD,MI
2021 Team                                MI
C/U/A                                Capped
Base Price                             2 CR
Sold Price                             8 CR
New Franchise              Rajasthan Royals
Name: 1, dtype: object
2 Set No.                                    1
Set Name                                   M
Player                           Pat Cummins
Country                            Australia
State Association                        NaN
Age                                       28
Specialism                       ALL-ROUNDER
Batting                                  RHB
Bowling                       RIGHT ARM Fast
IPL                                     37.0
Previous IPLTeam(s)              DD, MI, KKR
2021 Team                                KKR
C/U/A                                 Capped
Base Price                              2 CR
Sold Price                           7.25 CR
New Franchise          Kolkata Knight Riders
Name: 2, dtype: object
3 Set No.                               1
Set Name                              M
Player                   Shikhar Dhawan
Country                           India
State Association                  DDCA
Age                                  36
Specialism                      BATSMAN
Batting                             LHB
Bowling                               -
IPL                               192.0
Previous IPLTeam(s)    DCH, MI, SRH, DC
2021 Team                            DC
C/U/A                            Capped
Base Price                         2 CR
Sold Price                      8.25 CR
New Franchise              Punjab Kings
Name: 3, dtype: object
4 Set No.                                          1
Set Name                                         M
Player                              Faf Du Plessis
Country                               South Africa
State Association                              NaN
Age                                             37
Specialism                                 BATSMAN
Batting                                        RHB
Bowling                         RIGHT ARM Leg Spin
IPL                                          100.0
Previous IPLTeam(s)                       RPS, CSK
2021 Team                                      CSK
C/U/A                                       Capped
Base Price                                    2 CR
Sold Price                                    7 CR
New Franchise          Royal Challengers Bangalore
Name: 4, dtype: object
5 Set No.                                    1
Set Name                                   M
Player                          Shreyas Iyer
Country                                India
State Association                        MCA
Age                                       27
Specialism                           BATSMAN
Batting                                  RHB
Bowling                   RIGHT ARM Leg Spin
IPL                                     87.0
Previous IPLTeam(s)                       DC
2021 Team                                 DC
C/U/A                                 Capped
Base Price                              2 CR
Sold Price                          12.25 CR
New Franchise          Kolkata Knight Riders
Name: 5, dtype: object
6 Set No.                             1
Set Name                            M
Player                  Kagiso Rabada
Country                  South Africa
State Association                 NaN
Age                                26
Specialism                     BOWLER
Batting                           LHB
Bowling                RIGHT ARM Fast
IPL                              50.0
Previous IPLTeam(s)                DC
2021 Team                          DC
C/U/A                          Capped
Base Price                       2 CR
Sold Price                    9.25 CR
New Franchise            Punjab Kings
Name: 6, dtype: object
7 Set No.                                 1
Set Name                                M
Player                     Mohammad Shami
Country                             India
State Association                     CAB
Age                                    32
Specialism                         BOWLER
Batting                               RHB
Bowling                    RIGHT ARM Fast
IPL                                  77.0
Previous IPLTeam(s)    DCH, KKR, DD, PBKS
2021 Team                            PBKS
C/U/A                              Capped
Base Price                           2 CR
Sold Price                        6.25 CR
New Franchise              Gujarat Titans
Name: 7, dtype: object
8 Set No.                             1
Set Name                            M
Player                   David Warner
Country                     Australia
State Association                 NaN
Age                                35
Specialism                    BATSMAN
Batting                           LHB
Bowling                             -
IPL                             150.0
Previous IPLTeam(s)           DD, SRH
2021 Team                         SRH
C/U/A                          Capped
Base Price                       2 CR
Sold Price                    6.25 CR
New Franchise          Delhi Capitals
Name: 8, dtype: object
9 Set No.                                 2
Set Name                              BA1
Player                    Shimron Hetmyer
Country                       West Indies
State Association                     NaN
Age                                    25
Specialism                        BATSMAN
Batting                               LHB
Bowling                RIGHT ARM Leg Spin
IPL                                  31.0
Previous IPLTeam(s)               RCB, DC
2021 Team                              DC
C/U/A                              Capped
Base Price                         1.5 CR
Sold Price                         8.5 CR
New Franchise            Rajasthan Royals
Name: 9, dtype: object
10 Set No.                             2
Set Name                          BA1
Player                   David Miller
Country                  South Africa
State Association                 NaN
Age                                32
Specialism                    BATSMAN
Batting                           LHB
Bowling                             -
IPL                              89.0
Previous IPLTeam(s)          KXIP, RR
2021 Team                          RR
C/U/A                          Capped
Base Price                       1 CR
Sold Price                       3 CR
New Franchise          Gujarat Titans
Name: 10, dtype: object
11 Set No.                                 2
Set Name                              BA1
Player                   Devdutt Padikkal
Country                             India
State Association                    KSCA
Age                                    21
Specialism                        BATSMAN
Batting                               LHB
Bowling                RIGHT ARM Off Spin
IPL                                  29.0
Previous IPLTeam(s)                   RCB
2021 Team                             RCB
C/U/A                              Capped
Base Price                           2 CR
Sold Price                        7.75 CR
New Franchise            Rajasthan Royals
Name: 11, dtype: object
12 Set No.                                     2
Set Name                                  BA1
Player                          Manish Pandey
Country                                 India
State Association                        KSCA
Age                                        32
Specialism                            BATSMAN
Batting                                   RHB
Bowling                    RIGHT ARM Off Spin
IPL                                     154.0
Previous IPLTeam(s)    MI, RCB, PWI, KKR, SRH
2021 Team                                 SRH
C/U/A                                  Capped
Base Price                               1 CR
Sold Price                             4.6 CR
New Franchise            Lucknow Super Giants
Name: 12, dtype: object
13 Set No.                             2
Set Name                          BA1
Player                      Jason Roy
Country                       England
State Association                 NaN
Age                                31
Specialism                    BATSMAN
Batting                           RHB
Bowling                             -
IPL                              13.0
Previous IPLTeam(s)       GL, DC, SRH
2021 Team                         SRH
C/U/A                          Capped
Base Price                       2 CR
Sold Price                       2 CR
New Franchise          Gujarat Titans
Name: 13, dtype: object
14 Set No.                                         2
Set Name                                      BA1
Player                              Robin Uthappa
Country                                     India
State Association                             KCA
Age                                            36
Specialism                                BATSMAN
Batting                                       RHB
Bowling                                         -
IPL                                         193.0
Previous IPLTeam(s)    MI, PWI, RCB, KKR, RR, CSK
2021 Team                                     CSK
C/U/A                                      Capped
Base Price                                   2 CR
Sold Price                                   2 CR
New Franchise                 Chennai Super Kings
Name: 14, dtype: object
15 Set No.                                    3
Set Name                                 AL1
Player                          Dwayne Bravo
Country                          West Indies
State Association                        NaN
Age                                       38
Specialism                       ALL-ROUNDER
Batting                                  RHB
Bowling                RIGHT ARM Fast Medium
IPL                                    151.0
Previous IPLTeam(s)              MI, GL, CSK
2021 Team                                CSK
C/U/A                                 Capped
Base Price                              2 CR
Sold Price                            4.4 CR
New Franchise            Chennai Super Kings
Name: 15, dtype: object
16 Set No.                                          3
Set Name                                       AL1
Player                           Wanindu Hasaranga
Country                                  Sri Lanka
State Association                              NaN
Age                                             24
Specialism                             ALL-ROUNDER
Batting                                        RHB
Bowling                         RIGHT ARM Leg Spin
IPL                                            2.0
Previous IPLTeam(s)                            RCB
2021 Team                                      RCB
C/U/A                                       Capped
Base Price                                    1 CR
Sold Price                                10.75 CR
New Franchise          Royal Challengers Bangalore
Name: 16, dtype: object
17 Set No.                                   3
Set Name                                AL1
Player                         Jason Holder
Country                         West Indies
State Association                       NaN
Age                                      30
Specialism                      ALL-ROUNDER
Batting                                 RHB
Bowling                      RIGHT ARM Fast
IPL                                    26.0
Previous IPLTeam(s)           CSK, KKR, SRH
2021 Team                               SRH
C/U/A                                Capped
Base Price                           1.5 CR
Sold Price                          8.75 CR
New Franchise          Lucknow Super Giants
Name: 17, dtype: object
18 Set No.                                    3
Set Name                                 AL1
Player                        Mitchell Marsh
Country                            Australia
State Association                        NaN
Age                                       30
Specialism                       ALL-ROUNDER
Batting                                  RHB
Bowling                RIGHT ARM Fast Medium
IPL                                     21.0
Previous IPLTeam(s)       DCH, PWI, RPS, SRH
2021 Team                                NaN
C/U/A                                 Capped
Base Price                              2 CR
Sold Price                           6.50 CR
New Franchise                 Delhi Capitals
Name: 18, dtype: object
19 Set No.                                     3
Set Name                                  AL1
Player                          Krunal Pandya
Country                                 India
State Association                         BCA
Age                                        31
Specialism                        ALL-ROUNDER
Batting                                   LHB
Bowling                LEFT ARM Slow Orthodox
IPL                                      84.0
Previous IPLTeam(s)                        MI
2021 Team                                  MI
C/U/A                                  Capped
Base Price                               2 CR
Sold Price                            8.25 CR
New Franchise            Lucknow Super Giants
Name: 19, dtype: object
20 Set No.                                          3
Set Name                                       AL1
Player                               Harshal Patel
Country                                      India
State Association                              HCA
Age                                             31
Specialism                             ALL-ROUNDER
Batting                                        RHB
Bowling                      RIGHT ARM Fast Medium
IPL                                           63.0
Previous IPLTeam(s)                        DC, RCB
2021 Team                                      RCB
C/U/A                                       Capped
Base Price                                    2 CR
Sold Price                                10.75 CR
New Franchise          Royal Challengers Bangalore
Name: 20, dtype: object
21 Set No.                                    3
Set Name                                 AL1
Player                           Nitish Rana
Country                                India
State Association                       DDCA
Age                                       28
Specialism                       ALL-ROUNDER
Batting                                  LHB
Bowling                   RIGHT ARM Off Spin
IPL                                     77.0
Previous IPLTeam(s)                  MI, KKR
2021 Team                                KKR
C/U/A                                 Capped
Base Price                              1 CR
Sold Price                              8 CR
New Franchise          Kolkata Knight Riders
Name: 21, dtype: object
22 Set No.                                  3
Set Name                               AL1
Player                   Washington Sundar
Country                              India
State Association                     TNCA
Age                                     22
Specialism                     ALL-ROUNDER
Batting                                LHB
Bowling                 RIGHT ARM Off Spin
IPL                                   42.0
Previous IPLTeam(s)                    RCB
2021 Team                              RCB
C/U/A                               Capped
Base Price                          1.5 CR
Sold Price                         8.75 CR
New Franchise          Sunrisers Hyderabad
Name: 22, dtype: object
23 Set No.                             4
Set Name                          WK1
Player                 Jonny Bairstow
Country                       England
State Association                 NaN
Age                                32
Specialism               WICKETKEEPER
Batting                           RHB
Bowling                             -
IPL                              28.0
Previous IPLTeam(s)               SRH
2021 Team                         SRH
C/U/A                          Capped
Base Price                     1.5 CR
Sold Price                    6.75 CR
New Franchise            Punjab Kings
Name: 23, dtype: object
24 Set No.                                    4
Set Name                                 WK1
Player                          Sam Billings
Country                              England
State Association                        NaN
Age                                       30
Specialism                      WICKETKEEPER
Batting                                  RHB
Bowling                                    -
IPL                                     22.0
Previous IPLTeam(s)                  CSK, DC
2021 Team                                 DC
C/U/A                                 Capped
Base Price                              2 CR
Sold Price                              2 CR
New Franchise          Kolkata Knight Riders
Name: 24, dtype: object
25 Set No.                                          4
Set Name                                       WK1
Player                              Dinesh Karthik
Country                                      India
State Association                             TNCA
Age                                             36
Specialism                            WICKETKEEPER
Batting                                        RHB
Bowling                                          -
IPL                                          213.0
Previous IPLTeam(s)     KXIP, MI, DD, RCB, GL, KKR
2021 Team                                      KKR
C/U/A                                       Capped
Base Price                                    2 CR
Sold Price                                  5.5 CR
New Franchise          Royal Challengers Bangalore
Name: 25, dtype: object
26 Set No.                             4
Set Name                          WK1
Player                   Ishan Kishan
Country                         India
State Association                JSCA
Age                                23
Specialism               WICKETKEEPER
Batting                           LHB
Bowling                             -
IPL                              61.0
Previous IPLTeam(s)           GL , MI
2021 Team                          MI
C/U/A                          Capped
Base Price                       2 CR
Sold Price                   15.25 CR
New Franchise          Mumbai Indians
Name: 26, dtype: object
27 Set No.                                  4
Set Name                               WK1
Player                     Nicholas Pooran
Country                        West Indies
State Association                      NaN
Age                                     26
Specialism                    WICKETKEEPER
Batting                                LHB

In [ ]:
df.head()

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise
0,1,M,R Ashwin,India,TNCA,35,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,167.0,"CSK, RSP, KXIP, DC",DC,Capped,2 CR,5 CR,Rajasthan Royals
1,1,M,Trent Boult,New Zealand,NaN,32,BOWLER,RHB,LEFT ARM Fast Medium,62.0,"SRH, KKR, DD,MI",MI,Capped,2 CR,8 CR,Rajasthan Royals
2,1,M,Pat Cummins,Australia,NaN,28,ALL-ROUNDER,RHB,RIGHT ARM Fast,37.0,"DD, MI, KKR",KKR,Capped,2 CR,7.25 CR,Kolkata Knight Riders
3,1,M,Shikhar Dhawan,India,DDCA,36,BATSMAN,LHB,-,192.0,"DCH, MI, SRH, DC",DC,Capped,2 CR,8.25 CR,Punjab Kings
4,1,M,Faf Du Plessis,South Africa,NaN,37,BATSMAN,RHB,RIGHT ARM Leg Spin,100.0,"RPS, CSK",CSK,Capped,2 CR,7 CR,Royal Challengers Bangalore

In [ ]:
df.groupby(["State Association"]).mean()

                     Set No.        Age         IPL
State Association
ACA                 5.500000  31.000000  175.000000
ASCA                8.000000  20.000000   30.000000
BCA                28.000000  25.500000   84.000000
BICA               60.000000  29.000000         NaN
CAB                15.400000  27.200000   22.750000
CSCSCA             48.000000  30.000000    0.000000
DDCA               22.384615  25.153846   38.555556
GCA                25.000000  24.000000    0.000000
GUCA               17.000000  26.000000    2.000000
HCA                 7.500000  30.500000   61.000000
HPCA               23.500000  28.000000   13.000000
HYCA               29.500000  25.500000    0.000000
JKCA               27.000000  22.000000    1.000000
JSCA               18.750000  27.500000   46.000000
KCA                 7.000000  30.666667   72.000000
KSCA               16.166667  26.916667   47.750000
MACA               17.000000  23.500000   62.000000
MCA                19.444444  26.333333   52.571429
MPCA               14.000000  25.000000   25.000000
OCA                24.000000  25.000000         NaN
PCA                21.363636  26.000000   32.000000
RCA                24.625000  24.125000   41.400000
RSPB               31.000000  31.500000   34.000000
SCA                15.500000  29.000000   34.666667
TNCA               11.375000  29.250000   73.428571
UPCA               18.181818  23.545455   35.285714
UTCA               15.000000  28.000000   76.000000
VCA                27.000000  27.000000   40.333333

In [ ]:
df.groupby(["New Franchise"]).mean()

                               Set No.        Age        IPL
New Franchise
Chennai Super Kings          15.294118  28.470588  65.000000
Delhi Capitals               14.111111  26.222222  35.571429
Gujarat Titan                30.000000  31.000000  41.000000
Gujarat Titans               14.062500  28.312500  31.538462
Kolkata Knight Riders        22.700000  27.400000  41.928571
Lucknow Super Giants         17.933333  28.133333  49.090909
Luknow Super Giants          27.000000  23.000000   0.000000
Mumbai Indians               22.157895  25.105263  19.642857
Punjab Kings                 18.800000  27.200000  34.000000
Rajasthan Royals             18.578947  27.421053  47.692308
Royal Challengers Bangalore  16.157895  27.368421  32.529412
Sunrisers Hyderabad          17.578947  25.894737  27.000000

In [ ]:
df.groupby(["Country"]).sum().sort_values("IPL",ascending=False)

              Set No.   Age     IPL
Country
India            2353  3229  3906.0
Australia         179   360   282.0
West Indies       249   381   276.0
South Africa       56   194   247.0
New Zealand       192   319   158.0
England           173   340   146.0
Bangladesh          5    26    38.0
Sri Lanka          70   100     2.0
Afghanistan        33    38     0.0

In [ ]:
df['Specialism'].unique()

array(['ALL-ROUNDER', 'BOWLER', 'BATSMAN', 'WICKETKEEPER'], dtype=object)

In [ ]:
df['Specialism'].nunique()

4